# Generated by Django 5.0.1 on 2024-02-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastries',
            name='bestseller',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
