# Generated by Django 5.0.1 on 2024-02-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_pastries_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastries',
            name='modal_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pastries',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pastries',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
