# Generated by Django 5.0.1 on 2024-02-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_pastries_modal_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastries',
            name='new',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
