# Generated by Django 5.0.1 on 2024-02-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_pastries_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='mainpage/aboutuspics')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('modal_description', models.TextField(blank=True)),
                ('new', models.BooleanField()),
                ('bestseller', models.BooleanField()),
            ],
        ),
    ]
