# Generated by Django 5.0.1 on 2024-02-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0007_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
