# Generated by Django 5.0.1 on 2024-02-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_telephone_ordereditems_telephone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditems',
            old_name='first_name',
            new_name='firstName',
        ),
    ]
