# Generated by Django 5.0.1 on 2024-02-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_first_name_ordereditems_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditems',
            old_name='firstName',
            new_name='first_name',
        ),
    ]
