# Generated by Django 5.0.1 on 2024-02-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_firstname_ordereditems_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='unit_number',
            field=models.CharField(max_length=20),
        ),
    ]
