# Generated by Django 5.0.1 on 2024-02-20 06:24

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_ordereditems_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='date_ordered',
            field=models.DateTimeField(default=cart.models.OrderedItems.get_singapore_time),
        ),
    ]
