# Generated by Django 5.0.1 on 2024-02-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_ordereditems_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='items_ordered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
            preserve_default=False,
        ),
    ]
